name: Create release PRs

on:
  create

# See this page for available Xcode versions:
# https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md
env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer

jobs:
  build:

    runs-on: macos-13

    if: contains(github.ref, 'release') # allow to filter on release branches only
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.4
        bundler-cache: true

    - name: Bundle install
      run: bundle install

    - name: Prepare release
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_CI }}
      run: bundle exec fastlane create_release_pr
